### ISSUE TITLE
Presentation rascal-intro.pdf

### ISSUE THREAD

**Issue by Erblin-Ibrahimi** [cwi-swat/rascal-wax-on-wax-off#1]
Could you please upload a version of the pdf that adds the yellow comments page by page? Currently, it's overlapping quite a lot of the text.

**Comment by joukestoel** [comment]
I have just uploaded the expanded version of the slides to the 'official'  slides repo. You can now find it here -> https://github.com/cwi-swat/sle-rug/blob/master/slides/rascal-intro.pdf

Good luck!

**Comment by Erblin-Ibrahimi** [comment]
Thank you! I appreciate the fast response.
